export const BANNER_LIST_REQUEST = "BANNER_LIST_REQUEST";
export const BANNER_LIST_SUCCESS = "BANNER_LIST_SUCCESS";
export const BANNER_LIST_FAIL = "BANNER_LIST_FAIL";

export const BANNER_ADD_REQUEST = "BANNER_ADD_REQUEST";
export const BANNER_ADD_SUCCESS = "BANNER_ADD_SUCCESS";
export const BANNER_ADD_FAIL = "BANNER_ADD_FAIL";

export const BANNER_DELETE_REQUEST = "BANNER_DELETE_REQUEST";
export const BANNER_DELETE_SUCCESS = "BANNER_DELETE_SUCCESS";
export const BANNER_DELETE_FAIL = "BANNER_DELETE_FAIL";

export const VIDEO_BANNER_LIST_REQUEST = "VIDEO_BANNER_LIST_REQUEST";
export const VIDEO_BANNER_LIST_SUCCESS = "VIDEO_BANNER_LIST_SUCCESS";
export const VIDEO_BANNER_LIST_FAIL = "VIDEO_BANNER_LIST_FAIL";

export const VIDEO_BANNER_UPLOAD_REQUEST = "VIDEO_BANNER_UPLOAD_REQUEST";
export const VIDEO_BANNER_UPLOAD_SUCCESS = "VIDEO_BANNER_UPLOAD_SUCCESS";
export const VIDEO_BANNER_UPLOAD_FAIL = "VIDEO_BANNER_UPLOAD_FAIL";

export const VIDEO_BANNER_DELETE_REQUEST = "VIDEO_BANNER_DELETE_REQUEST";
export const VIDEO_BANNER_DELETE_SUCCESS = "VIDEO_BANNER_DELETE_SUCCESS";
export const VIDEO_BANNER_DELETE_FAIL = "VIDEO_BANNER_DELETE_FAIL";

export const USER_VIDEO_BANNER_LIST_REQUEST = "USER_VIDEO_BANNER_LIST_REQUEST";
export const USER_VIDEO_BANNER_LIST_SUCCESS = "USER_VIDEO_BANNER_LIST_SUCCESS";
export const USER_VIDEO_BANNER_LIST_FAIL = "USER_VIDEO_BANNER_LIST_FAIL";
